on:
  schedule:
    - cron:  '3/5 * * * *'
  workflow_dispatch:

jobs:
  fetch-appointments:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: |
        git branch -a
        mkdir dist
        cd dist
        pwd
        ls -la ..
        git clone .. .
        echo "Cloned"
        git branch -a
        git checkout gh-pages
        echo "pages"
        rm -rf .git
    - run: npm ci
    - run: npm run fetch
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
